research_task:
  description: >
    Analyze the problem about: {topic}. Find libraries, algorithms, or techniques that
    may be relevant to solving the problem.
  expected_output: >
    A summary of libraries, algorithms, and approaches.
  agent: code_researcher

write_code_task:
  description: >
    Write Python code that implements the recommendations of the code_researcher.
    Do not wrap code in '```python' and '```'.
  expected_output: >
    Python code that solves the problem.
    Properly format any explanations as valid python comment syntax.
  agent: code_writer

test_code_task:
  description: >
    Test the Python code to ensure it aligns with the problem requirements.
  expected_output: >
    A report on the tests that were chosen and their results, along with suggested fixes.
  agent: code_tester
