research_task:
  description: >
    1. Analyze the problem about: {topic}. Find libraries, algorithms, or techniques that
    may be relevant to solving the problem.
    2. Generate the python code that solves the problem.
  expected_output: >
    A summary of libraries, algorithms, and approaches.
  agent: code_researcher

test_code_task:
  description: >
    1. Analyze the code and generate tests of the intended behaviour.    
    2. Test the Python code to ensure it aligns with the problem requirements.
  expected_output: >
    A report on the tests that were generated including along with the results and with suggested fixes.
  agent: code_tester
